package ontology.impl;

import ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPedestrian_crossing_trash <br>
 * @version generated on Tue May 26 21:59:27 CEST 2020 by Michał Barczyk
 */
public class DefaultPedestrian_crossing_trash extends WrappedIndividualImpl implements Pedestrian_crossing_trash {

    public DefaultPedestrian_crossing_trash(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
